server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true

spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    virtual-host: test-host
    username: user
    password: password
    port: 5672
    template:
      exchange: test-exchange

application:
  rabbitmq:
    queue:
      robot-shop-in:
        routing-key: robot-shop-in
      robot-factory-in:
        topic: robot-factory-in