server:
  port: 9081

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true

spring:
  rabbitmq:
    host: localhost
    virtual-host: test-host
    username: user
    password: pass
    port: 5672
    template:
      exchange: test-exchange

application:
  rabbitmq:
    queue:
      robot-shop-out:
        topic: robot-shop-out
      robot-factory-in:
        topic: robot-factory-in
        routing-key: robot-factory-in