global:
  scrape_interval: 5s
  external_labels:
    monitor: 'codelab-monitor'
scrape_configs:
  - job_name: 'robot-factory'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'robot-factory:9081' ]
  - job_name: 'robot-shop'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'robot-shop:8082' ]
