global:
  scrape_interval: 5s
  external_labels:
    monitor: 'codelab-monitor'
scrape_configs:
  - job_name: 'robot-factory'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8081']
  - job_name: 'robot-shop'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8082' ]
